package com.cf.gp.dao;

import java.util.List;

import com.cf.gp.model.StockInfo;

public interface StockInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_info
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_info
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    int insert(StockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_info
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    int insertSelective(StockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_info
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    StockInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_info
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    int updateByPrimaryKeySelective(StockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_info
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    int updateByPrimaryKey(StockInfo record);
    
    List<StockInfo> selectAll();
}