package com.cf.gp.model;

import java.math.BigDecimal;
import java.util.Date;

public class StockPriceHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_price_history.ID
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_price_history.S_NAME
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_price_history.S_CODE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    private String sCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_price_history.S_DATE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    private Date sDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_price_history.S_PRICE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    private BigDecimal sPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_price_history.ID
     *
     * @return the value of t_stock_price_history.ID
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    
    private BigDecimal sOpen;
    private BigDecimal sHigh;
    private BigDecimal sLow;
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_price_history.ID
     *
     * @param id the value for t_stock_price_history.ID
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_price_history.S_NAME
     *
     * @return the value of t_stock_price_history.S_NAME
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_price_history.S_NAME
     *
     * @param sName the value for t_stock_price_history.S_NAME
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public void setsName(String sName) {
        this.sName = sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_price_history.S_CODE
     *
     * @return the value of t_stock_price_history.S_CODE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public String getsCode() {
        return sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_price_history.S_CODE
     *
     * @param sCode the value for t_stock_price_history.S_CODE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public void setsCode(String sCode) {
        this.sCode = sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_price_history.S_DATE
     *
     * @return the value of t_stock_price_history.S_DATE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public Date getsDate() {
        return sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_price_history.S_DATE
     *
     * @param sDate the value for t_stock_price_history.S_DATE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public void setsDate(Date sDate) {
        this.sDate = sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_price_history.S_PRICE
     *
     * @return the value of t_stock_price_history.S_PRICE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public BigDecimal getsPrice() {
        return sPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_price_history.S_PRICE
     *
     * @param sPrice the value for t_stock_price_history.S_PRICE
     *
     * @mbggenerated Tue Jan 09 14:17:07 CST 2018
     */
    public void setsPrice(BigDecimal sPrice) {
        this.sPrice = sPrice;
    }

	public BigDecimal getsOpen() {
		return sOpen;
	}

	public void setsOpen(BigDecimal sOpen) {
		this.sOpen = sOpen;
	}

	public BigDecimal getsHigh() {
		return sHigh;
	}

	public void setsHigh(BigDecimal sHigh) {
		this.sHigh = sHigh;
	}

	public BigDecimal getsLow() {
		return sLow;
	}

	public void setsLow(BigDecimal sLow) {
		this.sLow = sLow;
	}

}