package com.cf.gp.model;

import java.util.Date;

public class StockYes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_yes.ID
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_yes.S_NAME
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_yes.S_CODE
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    private String sCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_yes.S_DATE
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    private Date sDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_yes.ID
     *
     * @return the value of t_stock_yes.ID
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_yes.ID
     *
     * @param id the value for t_stock_yes.ID
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_yes.S_NAME
     *
     * @return the value of t_stock_yes.S_NAME
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_yes.S_NAME
     *
     * @param sName the value for t_stock_yes.S_NAME
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    public void setsName(String sName) {
        this.sName = sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_yes.S_CODE
     *
     * @return the value of t_stock_yes.S_CODE
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    public String getsCode() {
        return sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_yes.S_CODE
     *
     * @param sCode the value for t_stock_yes.S_CODE
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    public void setsCode(String sCode) {
        this.sCode = sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_yes.S_DATE
     *
     * @return the value of t_stock_yes.S_DATE
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    public Date getsDate() {
        return sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_yes.S_DATE
     *
     * @param sDate the value for t_stock_yes.S_DATE
     *
     * @mbggenerated Tue Jan 09 14:17:56 CST 2018
     */
    public void setsDate(Date sDate) {
        this.sDate = sDate;
    }
}