package com.cf.gp.model;

import java.util.Date;

public class StockInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_info.ID
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_info.S_NAME
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_info.S_CODE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    private String sCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_info.S_IS_STOP
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    private String sIsStop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_info.S_TYPE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    private String sType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_info.S_IS_DEL
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    private String sIsDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_info.S_DATE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    private Date sDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_info.ID
     *
     * @return the value of t_stock_info.ID
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_info.ID
     *
     * @param id the value for t_stock_info.ID
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_info.S_NAME
     *
     * @return the value of t_stock_info.S_NAME
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_info.S_NAME
     *
     * @param sName the value for t_stock_info.S_NAME
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public void setsName(String sName) {
        this.sName = sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_info.S_CODE
     *
     * @return the value of t_stock_info.S_CODE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public String getsCode() {
        return sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_info.S_CODE
     *
     * @param sCode the value for t_stock_info.S_CODE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public void setsCode(String sCode) {
        this.sCode = sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_info.S_IS_STOP
     *
     * @return the value of t_stock_info.S_IS_STOP
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public String getsIsStop() {
        return sIsStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_info.S_IS_STOP
     *
     * @param sIsStop the value for t_stock_info.S_IS_STOP
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public void setsIsStop(String sIsStop) {
        this.sIsStop = sIsStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_info.S_TYPE
     *
     * @return the value of t_stock_info.S_TYPE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public String getsType() {
        return sType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_info.S_TYPE
     *
     * @param sType the value for t_stock_info.S_TYPE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public void setsType(String sType) {
        this.sType = sType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_info.S_IS_DEL
     *
     * @return the value of t_stock_info.S_IS_DEL
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public String getsIsDel() {
        return sIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_info.S_IS_DEL
     *
     * @param sIsDel the value for t_stock_info.S_IS_DEL
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public void setsIsDel(String sIsDel) {
        this.sIsDel = sIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_info.S_DATE
     *
     * @return the value of t_stock_info.S_DATE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public Date getsDate() {
        return sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_info.S_DATE
     *
     * @param sDate the value for t_stock_info.S_DATE
     *
     * @mbggenerated Tue Jan 09 10:51:53 CST 2018
     */
    public void setsDate(Date sDate) {
        this.sDate = sDate;
    }
}